TRUNCATE TABLE CAT_MOVIMIENTO CASCADE;
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Descargado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Actualizado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Asignado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Escalado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Llamada', false);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Visita', false);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Email', false);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Otro Seguimiento', false);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Cerrado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Cancelado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Re-abierto', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Deasignado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Desescalado', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Incobrable', true);
INSERT INTO CAT_MOVIMIENTO(descripcion, system_based) VALUES('Recuperada', true);
