DROP TABLE IF EXISTS CAT_CLIENTE CASCADE;
CREATE TABLE IF NOT EXISTS CAT_CLIENTE (
	ID_CLIENTE INTEGER NOT NULL PRIMARY KEY,
	CD_CLIENTE VARCHAR(6),
	NOMBRE_CLIENTE VARCHAR(150),
	RUTA VARCHAR(20),
	DIA_PAGO VARCHAR(50)
);

GRANT ALL ON CAT_CLIENTE TO monfoll;

DROP TABLE IF EXISTS LOG_CLIENTE CASCADE;
CREATE TABLE IF NOT EXISTS LOG_CLIENTE (
	ID_LOG_CLIENTE SERIAL PRIMARY KEY,
	ID_CLIENTE INTEGER REFERENCES CAT_CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
	ES_LOCAL BOOLEAN,
	NOTA VARCHAR(250)
);

GRANT ALL ON LOG_CLIENTE TO monfoll;

DROP TABLE IF EXISTS CTRL_CUENTA CASCADE;
CREATE TABLE IF NOT EXISTS CTRL_CUENTA (
	ID_DOCO INTEGER NOT NULL PRIMARY KEY,
	F_DOCUMENTO DATE,
	F_VENCIMIENTO DATE,
	F_COBRO DATE,
	ID_CLIENTE INTEGER REFERENCES CAT_CLIENTE(ID_CLIENTE) NOT NULL,
	SERIE_DOCO VARCHAR(4),
	FOLIO_DOCO INTEGER,
	TIPO_DOCUMENTO VARCHAR(150),
	TIPO_COBRO VARCHAR(100),
	FACTURADO MONEY,
	SALDO MONEY,
	MONEDA VARCHAR(50),
	OBSERVACIONES VARCHAR(250),
	TS_DESCARGADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
GRANT ALL ON CTRL_CUENTA TO monfoll;

DROP TABLE IF EXISTS CTRL_ABONO CASCADE;
CREATE TABLE IF NOT EXISTS CTRL_ABONO(
	ID_ABONO INTEGER NOT NULL PRIMARY KEY,
	ID_DOCO INTEGER NOT NULL REFERENCES CTRL_CUENTA(ID_DOCO) ON DELETE CASCADE,
	TIPO_PAGO VARCHAR(150),
	IMPORTE_PAGO MONEY,
	FOLIO INTEGER,
	CONCEPTO VARCHAR(150),
	FECHA_DEPOSITO DATE,
	CUENTA VARCHAR(50)
);
GRANT ALL ON CTRL_ABONO TO monfoll;


DROP TABLE IF EXISTS CAT_COBRADOR CASCADE;
CREATE TABLE IF NOT EXISTS CAT_COBRADOR (
	ID_COBRADOR SERIAL PRIMARY KEY,
	NOMBRE_COBRADOR VARCHAR(150),
	ES_LOCAL BOOLEAN
);
GRANT ALL ON CAT_COBRADOR TO monfoll;

DROP TABLE IF EXISTS LOG_COBRADOR CASCADE;
CREATE TABLE IF NOT EXISTS LOG_COBRADOR (
	ID_LOG_COBRADOR SERIAL PRIMARY KEY,
	ID_COBRADOR INTEGER REFERENCES CAT_COBRADOR(ID_COBRADOR) ON DELETE CASCADE,
	NOTA VARCHAR(250)
);
GRANT ALL ON LOG_COBRADOR TO monfoll;

DROP TABLE IF EXISTS CTRL_ASIGNACION CASCADE;
CREATE TABLE IF NOT EXISTS CTRL_ASIGNACION (
	ID_ASIGNACION SERIAL PRIMARY KEY,
	ID_COBRADOR INTEGER NOT NULL REFERENCES CAT_COBRADOR(ID_COBRADOR) ON DELETE CASCADE,
	ID_DOCO INTEGER NOT NULL REFERENCES CTRL_CUENTA(ID_DOCO) ON DELETE CASCADE,
	TS_ASIGNADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 
GRANT ALL ON CTRL_ASIGNACION TO monfoll;

DROP TABLE IF EXISTS CAT_MOVIMIENTO CASCADE;
CREATE TABLE IF NOT EXISTS CAT_MOVIMIENTO (
	ID_MOVIMIENTO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(100)
);
GRANT ALL ON CAT_MOVIMIENTO TO monfoll;

DROP TABLE IF EXISTS CTRL_SEGUIMIENTO CASCADE;
CREATE TABLE IF NOT EXISTS CTRL_SEGUIMIENTO (
	ID_SEGUIMIENTO SERIAL PRIMARY KEY,
	ID_MOVIMIENTO INTEGER NOT NULL REFERENCES CAT_MOVIMIENTO(ID_MOVIMIENTO),
	ID_DOCO INTEGER NOT NULL REFERENCES CTRL_CUENTA(ID_DOCO) ON DELETE CASCADE,
	DESCRIPCION VARCHAR(250),
	TS_SEGUIMIENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
GRANT ALL ON CTRL_SEGUIMIENTO TO monfoll;