CREATE TABLE IF NOT EXISTS CAT_CLIENTE (
	ID_CLIENTE INTEGER NOT NULL PRIMARY KEY,
	CD_CLIENTE VARCHAR(6),
	NOMBRE_CLIENTE VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS LOG_CLIENTE (
	ID_LOG_CLIENTE SERIAL PRIMARY KEY,
	ID_CLIENTE INTEGER REFERENCES CAT_CLIENTE(ID_CLIENTE),
	EVENT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS CTRL_CUENTA (
	ID_DOCO INTEGER NOT NULL PRIMARY KEY,
	F_DOCUMENTO DATE,
	F_VENCIMIENTO DATE,
	F_COBRO DATE,
	RUTA INTEGER,
	ID_CLIENTE INTEGER REFERENCES CAT_CLIENTE(ID_CLIENTE) NOT NULL,
	SERIE_DOCO VARCHAR(4),
	FOLIO_DOCO INTEGER,
	TIPO_COBOR VARCHAR(100),
	FACTURADO MONEY,
	SALDO MONEY,
	MONEDA VARCHAR(50),
	OBSERVACIONES VARCHAR(250),
	ES_LOCAL BOOLEAN,
	TS_DESCARGADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CAT_COBRADOR (
	ID_COBRADOR SERIAL PRIMARY KEY,
	NOMBRE_COBRADOR VARCHAR(150),
	ES_LOCAL BOOLEAN
);

CREATE TABLE IF NOT EXISTS CTRL_ASIGNACION (
	ID_ASIGNACION SERIAL PRIMARY KEY,
	ID_COBRADOR INTEGER NOT NULL REFERENCES CAT_COBRADOR(ID_COBRADOR),
	ID_DOCO INTEGER NOT NULL REFERENCES CTRL_CUENTA(ID_DOCO),
	TS_ASIGNADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 

CREATE TABLE IF NOT EXISTS CAT_MOVIMIENTO (
	ID_MOVIMIENTO SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CTRL_SEGUIMIENTO (
	ID_SEGUIMIENTO SERIAL PRIMARY KEY,
	ID_MOVIMIENTO INTEGER NOT NULL REFERENCES CAT_MOVIMIENTO(ID_MOVIMIENTO),
	DESCRIPCION VARCHAR(250),
	TS_SEGUIMIENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);