TRUNCATE TABLE CAT_MOVIMIENTO CASCADE;
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Asignado');
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Escalado');
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Llamada');
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Visita');
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Email');
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Otro Seguimiento');
INSERT INTO CAT_MOVIMIENTO(DESCRIPCION) VALUES('Cerrado');